### Get All Clients
GET http://gratex.net/api/clients
Content-Type: application/json
X-API-KEY: 29a393cbea663961ce6771279c8206c3

### Get Client by ID (Assuming ID 1 exists)
GET http://gratex.net/api/clients?id=1
Content-Type: application/json
X-API-KEY: 29a393cbea663961ce6771279c8206c3
